server {
    # Listen on port 8080 explicitly as required by Google Cloud Run defaults
    listen 8080;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Basic SPA routing architecture
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Don't cache the service worker specifically
    location /sw.js {
        add_header Cache-Control "no-cache";
        try_files $uri =404;
    }
}
